Lesson: Webcam
allopez7/garagescript pull request #10
Opened 2017-08-23 03:38 UTC by allopez7

2017-08-23 20:13 UTC, seemcat requested changes

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +  <pre id="browserViewText"></pre>
I would put all of the webcam stuff inside of a `<div>` tag. We use DIV in HTML when we want to group sections of HTML elements together; it's good programming syntax.

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +      const nam = document.getElementById('name').value;
I don't think you need to be afraid to name variables the same name as its' ID. It does not influence the code at all. If you understand your code well enough you'd know whether `name` is an ID or a variable. Besides, `nam` and `com` are confusing names. When you start working on the LLIP App, they will tell you to give it the proper variable names; `name` and `comment`.

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +window.setInterval(()=>{
setInterval takes in two parameters; the function and the interval time. Usually if the function is long enough, I will just define the function elsewhere. For example, I'll define the function `const getTextFile = () => { _YOUR CODE_ }` and so that when I call setInterval it would look easier to read: `window.setInterval(getTextFile, 1000);`

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +const vid = document.getElementById('v');
Again, write more clear variables or Id's.

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +  const nam = document.getElementById('name').value;
Why do you need the name? This isn't lesson 9. All you have to do is write this picture into a file, not add any text. So why is name necessary?

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +  const contex = canv.getContext('2d');
context

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +  const img = new XMLHttpRequest();
Why are you calling the instance of you XMLHttpRequest object img? It's confusing. A better name would be xhttp. Because that's exactly what it is; an instance of the XMLHttpRequest; NOT an image.

2017-08-23 20:13 UTC, seemcat commented on Webcam/public/index.html
> +  const can = canv.toDataURL('image/png');
`canvas.toDataURL('image/png');` gives you back the image's data URL. So a better name for this is `dataURL`, not `can`. _What is can?_ Please give **proper** and **fitting** variable names.

2017-08-23 22:00 UTC, SahilKalra98 approved these changes

2017-08-23 22:04 UTC, SahilKalra98 commented on Webcam/public/index.html
> +
remove empty line

2017-08-23 22:04 UTC, SahilKalra98 commented on Webcam/public/index.html
> +
remove empty line

2017-08-24 00:43 UTC, seemcat approved these changes

2017-08-24 01:42 UTC, merged